name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'hosting/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hosting/**' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  DIGITALOCEAN_TOKEN: ${{ secrets.DO_API_KEY }}

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: hosting/go.sum

    - name: Setup Pulumi CLI
      uses: pulumi/actions@v4

    - name: Configure AWS for Pulumi backend (if using S3)
      if: env.AWS_ACCESS_KEY_ID != ''
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    - name: Build infrastructure program
      working-directory: hosting
      run: |
        mkdir -p bin
        go mod download
        go build -o bin/cgc-hosting .

    - name: Deploy to development
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: hosting
      run: |
        pulumi stack select dev --create
        pulumi config set digitalocean:region nyc3
        pulumi config set cgc-hosting:ssh_key_name "${{ secrets.SSH_KEY_NAME }}"
        pulumi up --yes
      env:
        PULUMI_STACK: dev

    - name: Preview changes (PR)
      if: github.event_name == 'pull_request'
      working-directory: hosting
      run: |
        pulumi stack select dev --create
        pulumi config set digitalocean:region nyc3
        pulumi config set cgc-hosting:ssh_key_name "${{ secrets.SSH_KEY_NAME }}"
        pulumi preview

    - name: Deploy to specific environment (manual)
      if: github.event_name == 'workflow_dispatch'
      working-directory: hosting
      run: |
        pulumi stack select ${{ github.event.inputs.environment }} --create
        pulumi config set digitalocean:region nyc3
        pulumi config set cgc-hosting:ssh_key_name "${{ secrets.SSH_KEY_NAME }}"
        pulumi up --yes
      env:
        PULUMI_STACK: ${{ github.event.inputs.environment }}

    - name: Export stack outputs
      if: success()
      working-directory: hosting
      run: |
        echo "## Infrastructure Outputs" >> $GITHUB_STEP_SUMMARY
        echo "### Load Balancer IP" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        pulumi stack output loadBalancerIp >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "### Backend Droplet IP" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        pulumi stack output backendDropletIp >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "### Frontend Droplet IP" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        pulumi stack output frontendDropletIp >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY